### ISSUE TITLE
Please add typescript definitions

### ISSUE THREAD

**Issue by mrjbj** [borisdiakur/rerror#1]
I really like this module!  Thanks for creating it.  Curious if possible to add typescript definitions. I tried npm install @types/rerror but couldn't find anything. I'd try to do it myself, but unfortunately not knowledgeable just yet.  Will try to do later as I learn more, though.  Nice module.  Thanks!

**Comment by leafoflegend** [comment]
Doubling down here - since you modify the global object, it makes this library very annoying to use in TS. You should consider exporting your error as a thing that can be imported and including a definitions file.

**Comment by borisdiakur** [comment]
Whooops, saw the first notification and then totally forgot to come back to this issue. So thanks for “doubling down” @leafoflegend and for creating the issue @mrjbj. I will definitely try to make some time to address it as soon as I can.

**Comment by borisdiakur** [comment]
Trying to publish v2.0.0 though the registry doesn’t let me. https://status.npmjs.org says:

> Update - We continue to investigate issues with loading npmjs.com and publishing packages for logged-in users
Sep 21, 18:18 UTC

Will try again later.

**Comment by borisdiakur** [comment]
Just pulished v2.0.0 with a .d.ts file included. Please try it out. Breaking change is: RError is not available via the global object anymore when used in a module system environment. Instead you have to require or import it in order to use it.
🚀
